Lab12/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab12.Models
{
    public class Persona
    {
        public int PersonaID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public DateTime FechaNac { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
    }
}

Lab12/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab12.Models;

namespace Lab12.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listar()
        {
            List<Persona> personas = new List<Persona>();

            personas.Add(new Persona
            {
                PersonaID = 1,
                Nombre = "Juan",
                Apellido = "Perez",
                Direccion = "Av. Evergen 123",
                FechaNac = Convert.ToDateTime("1997-11-07"),
                Email = "juan@mail.com"
            });

            personas.Add(new Persona
            {
                PersonaID = 2,
                Nombre = "María",
                Apellido = "Salas",
                Direccion = "Av. Progreso 325",
                FechaNac = Convert.ToDateTime("1995-10-28"),
                Email = "maria@mail.com"
            });

            personas.Add(new Persona
            {
                PersonaID = 3,
                Nombre = "Carlos",
                Apellido = "Martinez",
                Direccion = "Av. Los manzanos 3101",
                FechaNac = Convert.ToDateTime("1982-02-14"),
                Email = "carlos@mail.com"
            });

            return View(personas);
        }

    }
}

Lab12/Views/Persona/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Daniel Paredes - Personas</h2>

@Html.ActionLink("Listar personas", "Listar", "Persona")

Lab12/Views/Persona/Listar.cshtml
@Model List<Lab12.Models.Persona>
    @{
        ViewBag.Title = "Listar";
    }

    <h2>Listado de personas</h2>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">PersonaID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Fecha Nacimiento</th>
                <th scope="col">Dirección</th>
                <th scope="col">Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var persona in Model)
            {
                <tr>
                    <th scope="row">@persona.PersonaID</th>
                    <td>@persona.Nombre</td>
                    <td>@persona.Apellido</td>
                    <td>@persona.FechaNac</td>
                    <td>@persona.Direccion</td>
                    <td>@persona.Email</td>
                </tr>
            }
        </tbody>
    </table>